### ISSUE TITLE
Set current not working with sensor data

### ISSUE THREAD

**Issue by zaubererty** [cathiele/homeassistant-goecharger#15]
I have a PV solar system und would like change the charge current dynamically.
Here my config:
This is the conversion from power to current for a tow line charger
```
  - platform: template
    sensors:
      solar_charge_current:
        entity_id: sensor.kostal_pv_power
        friendly_name: "Solar Charge Current"
        unit_of_measurement: 'A'
        value_template: "{{ (states('sensor.kostal_pv_power')|int / 230 / 2)|round(0) }}"
```

This is my automation
```
- id: '1592747090585'
  alias: Set Solar Charge current
  description: ''
  trigger:
  - above: '6'
    below: '32'
    entity_id: sensor.solar_charge_current
    platform: numeric_state
  condition: []
  action:
  - data:
      enitiy_id: sensor.goecharger_0123456_charger_max_current
      max_current: '{{ trigger.to_state.state }}'
    service: goecharger.set_max_current
```

```
2020-06-25 08:14:24 ERROR (MainThread) [homeassistant.components.automation] Set Solar Charge current: Error executing script. Unexpected error for call_service at pos 1: invalid literal for int() with base 10: '{{ trigger.to_state.state }}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1298, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/goecharger/__init__.py", line 55, in handle_set_max_current
    maxCurrent = int(maxCurrent)
ValueError: invalid literal for int() with base 10: '{{ trigger.to_state.state }}'
```

Any hint?

**Comment by cathiele** [comment]
Do you get an error message in the logs?

**Comment by zaubererty** [comment]
Updated with the log
I tried to bring in the value in several ways:
-  '{{ trigger.to_state.state }}'
- sensor.solar_charge_current
- {{sensor.solar_charge_current}}

non of them worked

**Comment by zaubererty** [comment]
Found a solution:
```
- id: '1592347090525'
  alias: Charge current
  description: Set Solar Charge current
  trigger:
  - above: '5'
    below: '33'
    entity_id: sensor.solar_charge_current
    platform: numeric_state
  condition: []
  action:
  - data_template:
      max_current: '{{ states(''sensor.solar_charge_current'')|int }}'
    service: goecharger.set_max_current
```

**Comment by zaubererty** [comment]
```
```

```
