### ISSUE TITLE
goecharger connection not established when HA restarts

### ISSUE THREAD

**Issue by maulwuff** [cathiele/homeassistant-goecharger#27]
I had a running charging sesssion and restartet HA. 
After that, goecharger components never came back. Is this expected? 
Is it possible to rescan for an existing goecharger when HA starts, rather than to start HA and then plug in goecharger?

**Comment by maulwuff** [comment]
here is the log from HA.
looks like it didn't find the charger? This was at 16:50, the charging session lasted until ~23:00 Today I still have no values (Entität nicht verfügbar)


```


Logger: homeassistant.setup
Source: custom_components/goecharger/__init__.py:43
First occurred: 9. Dezember 2020, 16:51:14 (1 occurrences)
Last logged: 9. Dezember 2020, 16:51:14
Error during setup of component goecharger

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.0.107', port=80): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/goecharger/__init__.py", line 43, in setup
    status = goeCharger.requestStatus()
  File "/usr/local/lib/python3.8/site-packages/goecharger/goecharger.py", line 278, in requestStatus
    status = self.__queryStatusApi()
  File "/usr/local/lib/python3.8/site-packages/goecharger/goecharger.py", line 182, in __queryStatusApi
    statusRequest = requests.get("http://%s/status" % self.host, timeout=5)  # TODO: Configurable Timeout
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.107', port=80): Read timed out. (read timeout=5)

```

**Comment by cathiele** [comment]
with the actual version this should not happen. please verify it and open a new issue if this is still a problem
