### ISSUE TITLE
Unable to fetch state for Charger

### ISSUE THREAD

**Issue by tuxpoldo** [cathiele/homeassistant-goecharger#39]
Home Assistant 2021.6.3
go-eCharger Firmware Version 040.0
homeassistant-goecharger Version 0.22.0 installed from HACS

Device and entities are created. All entities are unavailable.

```
2021-06-11 09:40:14 ERROR (MainThread) [custom_components.goecharger] Unable to fetch state for Charger wallbox
2021-06-11 09:40:14 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform goecharger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/config/custom_components/goecharger/sensor.py", line 191, in state
    return self.coordinator.data[self._chargername][self._attribute]
KeyError: 'wallbox'
2021-06-11 09:40:14 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform goecharger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 772, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/goecharger/switch.py", line 122, in is_on
    return True if self.coordinator.data[self._chargername][self._attribute] == "on" else False
KeyError: 'wallbox'
2021-06-11 09:40:14 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up goecharger platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/config/custom_components/goecharger/sensor.py", line 191, in state
    return self.coordinator.data[self._chargername][self._attribute]
KeyError: 'wallbox'
2021-06-11 09:40:14 ERROR (MainThread) [homeassistant.components.switch] Error while setting up goecharger platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 772, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/goecharger/switch.py", line 122, in is_on
    return True if self.coordinator.data[self._chargername][self._attribute] == "on" else False
KeyError: 'wallbox'
2021-06-11 09:40:37 ERROR (MainThread) [custom_components.goecharger] Unable to fetch state for Charger wallbox
2021-06-11 09:40:37 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/config/custom_components/goecharger/sensor.py", line 191, in state
    return self.coordinator.data[self._chargername][self._attribute]
KeyError: 'wallbox'
2021-06-11 09:41:00 ERROR (MainThread) [custom_components.goecharger] Unable to fetch state for Charger wallbox
2021-06-11 09:41:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/config/custom_components/goecharger/sensor.py", line 191, in state
    return self.coordinator.data[self._chargername][self._attribute]
KeyError: 'wallbox'
```

**Comment by Jpsy** [comment]
User the go-e app to activate the API v1 in the settings of the go-e charger.
This is definitely missing in the readme of this custom integration. I will try to create a PR asap.

**Comment by wuschi1983** [comment]
same Problem here. Is there a solution?
