### ISSUE TITLE
Unexpected error fetching goecharger data: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by pschyrembel258** [cathiele/homeassistant-goecharger#41]
After restart of home assistant all entities are unavailable. In the logs it says only
Unexpected error fetching goecharger data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/goecharger/__init__.py", line 87, in fetch_states
    fetchedStatus = await self._hass.async_add_executor_job(goeChargers[chargerName].requestStatus)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/goecharger/goecharger.py", line 308, in requestStatus
    status = self.__queryStatusApi()
  File "/usr/local/lib/python3.9/site-packages/goecharger/goecharger.py", line 204, in __queryStatusApi
    status = statusRequest.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by b10126** [comment]
Hi altogether,
this occured within my installation today as well.
Until yesterday my installation (with box HW V2, FW 41) worked properly for half an year. No issues during restarts etc.

Yesterday I added an 2nd wallbox (HW V3, Fw v59) and got it integrated into homeassistant, all entities were created as expected.

By today both wallboxes are not available via HA, the access via the go app works fine. Restart brought the same results, no network issues. 

If you have any suggestions how to proceed I would appreciate about any information. 
I'll let you know if the problem solves itself somehow.... 

Btw, thanks for this great smoothy integration!

**Comment by b10126** [comment]
So I don't know what happened, but w/o any additional tasks it works fine now. Cool stuff! Thanks a lot for your work!
