### ISSUE TITLE
Error in HA Log

### ISSUE THREAD

**Issue by r100gs** [cathiele/homeassistant-goecharger#60]
I get following error in HA Log with the integration

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.goecharger
Source: custom_components/goecharger/__init__.py:87
Integration: go-eCharger (documentation, issues)
First occurred: 06:43:25 (1 occurrences)
Last logged: 06:43:25

Unexpected error fetching goecharger data: float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/goecharger/__init__.py", line 87, in fetch_states
    fetchedStatus = await self._hass.async_add_executor_job(goeChargers[chargerName].requestStatus)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/goecharger/goecharger.py", line 309, in requestStatus
    response = GoeChargerStatusMapper().mapApiStatusResponse(status)
  File "/usr/local/lib/python3.9/site-packages/goecharger/goecharger.py", line 50, in mapApiStatusResponse
    t1 = float(valueOrNull(status.get('tma', []), GoeCharger.TMA_1))
TypeError: float() argument must be a string or a number, not 'NoneType'
`

**Versions (please complete the following information):**
 - home-assistant 2022.3.8
 - Charger Hardware: [v3]
 - Charger Firmware Version: [0.53.1]
 - Plugin Version: [e.g. 0.24.1]

Best regards,
Stefan

**Comment by pschyrembel258** [comment]
I am experiencing the same error in the logs.

**Comment by cathiele** [comment]
is this still a problem with 0.25.2? if not, how can i reproduce it?
