### ISSUE TITLE
cannot add integration anymore v0.25.0

### ISSUE THREAD

**Issue by r100gs** [cathiele/homeassistant-goecharger#65]
After the update to version v0.25.0 I cannot add the integration anymore

go to new integration
try to add goe integration 
fill out everything
press enter

 - home-assistant []
 - Charger Hardware: [v3]
 - Charger Firmware Version: [0.53.1]
 - Plugin Version: [0.25]

**Additional context**
error message:
User input malformed: expected float for dictionary value @ data['correction_factor']

**Comment by diegodanado** [comment]
I have Theo same Error

**Comment by stepir** [comment]
same here

**Comment by temesinko** [comment]
I've upgraded from 0.24.1 to 0.25.0 (so the integration was upgraded not freshly installed) and I have the following error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/goecharger/sensor.py", line 164, in async_setup_entry
    async_add_entities(_create_sensors_for_charger(chargerName, hass, config[CONF_CORRECTION_FACTOR]))
KeyError: 'correction_factor'
```

When trying to edit the configuration in the backend, following error message is shown:

![image](https://user-images.githubusercontent.com/14085424/164445119-663bdaec-1237-40b3-a508-2b8b5528783a.png)

The response of the related XHR request looks the following:

![image](https://user-images.githubusercontent.com/14085424/164445247-c4cd1993-a065-4bc1-a3d4-fd4268645368.png)

The problems are related to the recent changes regarding `correction_factor` configuration variable.

**Comment by cathiele** [comment]
Please test version 0.25.1

**Comment by stepir** [comment]
@cathiele now it works - can you please advise who the factor should be used? need to be lower than 1 (1 wont be accepted during setup) to be valid.

**Comment by temesinko** [comment]
@cathiele Integration itself works now and initializes correctly, but the config flow (in my case after upgrading, not a fresh install) is still broken. I'll have a look at this tonight.

**Comment by cathiele** [comment]
finally i had time to fix it. 0.25.2 should have a working config flow.

Older Chargers, like mine V2 charger, have incorrect power calculations. mine is way to low. So with setting the correction factor to values other than 1.0 you can correct the api values by a factor. the uncorrected values are still available as the original attributes.
